---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orc
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrator
subjects:
- kind: ServiceAccount
  name: {{ include "orchestrator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
