apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 10008
      targetPort: raft
      protocol: TCP
      name: raft
  clusterIP: None
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    {{- include "orchestrator.selectorLabels" . | nindent 4 }}
